name = "myblog"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
route = "yourdomain.com/*"

[env.preview]
route = "preview.yourdomain.com/*"

# 构建配置
[build]
command = "npm run build"
output_dir = "dist"

# 环境变量
[vars]
NODE_VERSION = "18"
NPM_VERSION = "9"